"""Generated by render.py — the ONLY place app identity lives. Do not hardcode elsewhere."""
DATABASE          = "DEMO_DYNAMICS_APP"
SCHEMA            = "PUBLIC"
SERVICE_FQN       = "DEMO_DYNAMICS_APP.PUBLIC.COMPANY_KB_SEARCH"
KB_TABLE          = "COMPANY_KNOWLEDGE_BASE"
KB_CONTENT_COL    = "CONTENT"
LLM_MODEL         = "mistral-large2"
COMPANY_NAME      = "Northwind Manufacturing"
APP_TITLE         = "Northwind ERP"
APP_ICON          = "🏭"
ASSISTANT_INTRO   = "Ask me about payment terms, returns, credit policy, and the product catalog."
CHAT_PLACEHOLDER  = "Ask about payment terms, returns, products..."
SUGGESTED_PROMPTS = ["What are our standard payment terms?", "What is the returns / RMA policy?", "How is a customer credit limit set?"]
SEARCH_COLUMNS    = ["CONTENT", "TITLE", "CATEGORY"]
SEARCH_LIMIT      = 3
