#!/usr/bin/env python3
"""Offline Bronze loader — the no-tunnel twin of BRONZE.SP_INGEST_ALL_BRONZE.

Builds the same OmniHR + Harvest graph the mock API serves, serializes each record
with the SAME `endpoints.py` serializers, and emits a SQL file that loads the raw
JSON into `BRONZE.<entity>` VARIANT tables — byte-for-byte the shape the live API
ingest produces. Then `CALL SILVER.SP_BUILD_SILVER()` flattens it exactly as in the
live DEMO path. This is the 7ptrial path: a trial account (which can't use an External
Access Integration) demos the FULL Bronze -> Silver -> Gold flow, fed from local JSON
instead of the HTTP tunnel.

    python3 seed_bronze.py --out bronze_seed.sql [--seed 42] [--today YYYY-MM-DD]
                           [--database DEMO_EMPLOYEE_APP]
    python3 seed_bronze.py --selftest     # assert the JSON matches the flatten field-map paths

The Bronze it writes is identical to the API path, so `SILVER.SP_BUILD_SILVER`,
`04_gold.sql`, and `05_semantic_analyst.sql` all run unchanged afterwards.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import date
from pathlib import Path

# Reuse the mock API's data engine + serializers (they live in ../../mock_api) so the
# Bronze JSON is byte-identical to what the live API ingest produces.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent / "mock_api"))
import dataset                                  # builds the FK-coherent graph (reuses _seedlib)
from endpoints import endpoint_specs           # the SAME serializers the mock API serves

DB_DEFAULT = "DEMO_EMPLOYEE_APP"
BATCH = 500                                     # rows per INSERT, mirrors the seeder's batching


def _sql_str(s: str) -> str:
    """A single-quoted SQL string literal (double any embedded quote)."""
    return "'" + s.replace("'", "''") + "'"


def _records(seed: int = 42, today: date | None = None):
    """[(table, source, api_path, [json_record, ...]), ...] using the API serializers."""
    _order, data, _cols, pk, _src = dataset.build(seed=seed, today=today)
    out = []
    for s in endpoint_specs(pk):
        ser, t = s["serializer"], s["table"]
        out.append((t, s["source"], s["path"],
                    [json.dumps(ser(r), default=str) for r in data[t]]))
    return out


def build_sql(db: str, seed: int, today: date | None) -> str:
    recs = _records(seed, today)
    L = [
        "-- Generated by seed_bronze.py — offline Bronze load (no tunnel / no EAI).",
        "-- Mirrors BRONZE.SP_INGEST_ALL_BRONZE: same JSON, same BRONZE.<t> VARIANT shape,",
        "-- so SILVER.SP_BUILD_SILVER + 04_gold + 05_semantic run unchanged afterwards.",
        "USE ROLE ACCOUNTADMIN;",
        f"USE DATABASE {db};",
        "CREATE SCHEMA IF NOT EXISTS BRONZE;",
        "",
        "-- Endpoint registry — SILVER.SP_BUILD_SILVER iterates this to flatten each table.",
        "CREATE OR REPLACE TABLE BRONZE.BRONZE_ENDPOINTS (SOURCE STRING, API_PATH STRING, TABLE_NAME STRING);",
        "INSERT INTO BRONZE.BRONZE_ENDPOINTS (SOURCE, API_PATH, TABLE_NAME) VALUES\n  "
        + ",\n  ".join(f"({_sql_str(src)}, {_sql_str(path)}, {_sql_str(t)})"
                       for t, src, path, _ in recs) + ";",
        "",
    ]
    for t, src, path, jsons in recs:
        L.append(f"-- {t}: {len(jsons)} records")
        L.append(f"CREATE TABLE IF NOT EXISTS BRONZE.{t} "
                 f"(PAYLOAD VARIANT, _SOURCE STRING, _PATH STRING, _LOADED_AT TIMESTAMP_NTZ);")
        L.append(f"TRUNCATE TABLE BRONZE.{t};")
        for i in range(0, len(jsons), BATCH):
            vals = ",\n  ".join(f"({_sql_str(j)}, {_sql_str(src)}, {_sql_str(path)})"
                                for j in jsons[i:i + BATCH])
            L.append(f"INSERT INTO BRONZE.{t} (PAYLOAD, _SOURCE, _PATH, _LOADED_AT)\n"
                     f"SELECT PARSE_JSON($1), $2, $3, CURRENT_TIMESTAMP() FROM VALUES\n  {vals};")
        L.append("")
    return "\n".join(L)


def _selftest() -> int:
    """The seeded JSON must resolve at the exact paths SP_FLATTEN reads (field map + lowercase fallback)."""
    recs = {t: jsons for t, _s, _p, jsons in _records()}
    emp = json.loads(recs["EMPLOYEES"][0])
    assert emp["work_email"] and emp["position"]["name"] and emp["system_id"], "employee nested shape"
    assert "reporting_manager" in emp, "employee manager path"
    te = json.loads(recs["TIME_ENTRIES"][0])
    assert te["user"]["id"] is not None and "billable" in te, "time_entry nested shape"
    bu = json.loads(recs["BUSINESS_UNITS"][0])
    assert bu and all(k == k.lower() for k in bu), "flat keys must be lowercase (SP_FLATTEN fallback)"
    total = sum(len(j) for j in recs.values())
    print(f"✓ selftest passed: {len(recs)} tables, {total} records serialize to "
          f"field-map-compatible JSON")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="Offline Bronze loader (no-tunnel twin of SP_INGEST_ALL_BRONZE).")
    ap.add_argument("--out", help="write the SQL here (default: stdout)")
    ap.add_argument("--database", default=DB_DEFAULT)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--today", help="YYYY-MM-DD (default: real today)")
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args()
    if args.selftest:
        return _selftest()
    today = date.fromisoformat(args.today) if args.today else None
    sql = build_sql(args.database, args.seed, today)
    if args.out:
        Path(args.out).write_text(sql, encoding="utf-8")
        print(f"✓ wrote {args.out}")
    else:
        sys.stdout.write(sql)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
