-- =====================================================================
-- 00_setup.sql  --  From-scratch infrastructure for the DASHBOARD_SPS app
-- (Employee 360 / DEMO_EMPLOYEE_APP.PUBLIC).
--
-- Captured from the live DEMO account (sevenpeaks_partner_demo) via
-- GET_DDL on 2026-06-24, then made non-destructive: every object uses
-- IF NOT EXISTS / CREATE ... IF NOT EXISTS so re-running NEVER drops data.
-- This file creates STRUCTURE ONLY (warehouses, db, schema, stages, the
-- 40 tables empty). Demo data already lives in the account; see the data
-- note at the bottom to (re)load from a stage.
--
-- Run order:  00_setup.sql  ->  01_document_ingestion.sql  ->  deploy the
-- Streamlit app (see ../snowflake.yml / ../README.md).
--
-- Two warehouses, by design (matches the live account):
--   DEMO_EMPLOYEE_APP  -- the Streamlit app's query_warehouse
--   DEMO_WH            -- the Cortex Search service + ingestion tasks
-- Objects are owned by ACCOUNTADMIN in the live account (the app runs with
-- owner's rights and must write the chat tables), so create them as such.
-- =====================================================================
USE ROLE ACCOUNTADMIN;

-- 1) Warehouses ------------------------------------------------------
CREATE WAREHOUSE IF NOT EXISTS DEMO_EMPLOYEE_APP
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 300 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Query warehouse for the DASHBOARD_SPS Streamlit app';
CREATE WAREHOUSE IF NOT EXISTS DEMO_WH
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Cortex Search service + document-ingestion tasks';

-- 2) Database + schema ----------------------------------------------
CREATE DATABASE IF NOT EXISTS DEMO_EMPLOYEE_APP
    COMMENT = 'Employee 360 / DASHBOARD_SPS demo (synthetic data)';
CREATE SCHEMA IF NOT EXISTS DEMO_EMPLOYEE_APP.PUBLIC;
USE SCHEMA DEMO_EMPLOYEE_APP.PUBLIC;
USE WAREHOUSE DEMO_WH;

-- 3) Stages ----------------------------------------------------------
CREATE STAGE IF NOT EXISTS STREAMLIT_STAGE
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Streamlit app artifacts';
CREATE STAGE IF NOT EXISTS DEMO_SEED_STAGE
    DIRECTORY = (ENABLE = TRUE)
    FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1 NULL_IF = ('', 'NULL', 'null'))
    COMMENT = 'Seed CSV landing zone for COPY INTO (data reload)';
-- COMPANY_DOCS needs SSE so CORTEX.PARSE_DOCUMENT can read it (used by 01).
CREATE STAGE IF NOT EXISTS COMPANY_DOCS
    DIRECTORY = (ENABLE = TRUE)
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
    COMMENT = 'Drop company docs here; parsed + chunked + indexed by Cortex Search (see 01_document_ingestion.sql)';

-- 4) Dashboard tables (35) ------------------------------------------
CREATE TABLE IF NOT EXISTS AVAILABILITY (
	AVAIL_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	EMPLOYEE_ID NUMBER(38,0),
	AVAIL_DATE DATE,
	STATUS VARCHAR(20),
	primary key (AVAIL_ID)
);
CREATE TABLE IF NOT EXISTS BUSINESS_UNITS (
	BU_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	NAME VARCHAR(100) NOT NULL,
	HEAD_USER_ID NUMBER(38,0),
	primary key (BU_ID)
);
CREATE TABLE IF NOT EXISTS CANDIDATES (
	CANDIDATE_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	JOB_ID NUMBER(38,0),
	FIRST_NAME VARCHAR(80),
	LAST_NAME VARCHAR(80),
	EMAIL VARCHAR(150),
	STAGE VARCHAR(40),
	STATUS VARCHAR(20),
	SOURCE VARCHAR(60),
	APPLIED_DATE DATE,
	RATING NUMBER(2,1),
	primary key (CANDIDATE_ID)
);
CREATE TABLE IF NOT EXISTS CANDIDATE_SOURCES (
	SOURCE_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	NAME VARCHAR(60),
	CATEGORY VARCHAR(40),
	primary key (SOURCE_ID)
);
CREATE TABLE IF NOT EXISTS CANDIDATE_SOURCE_CATEGORIES (
	CATEGORY_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	NAME VARCHAR(40),
	primary key (CATEGORY_ID)
);
CREATE TABLE IF NOT EXISTS CLIENTS (
	CLIENT_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	NAME VARCHAR(120),
	INDUSTRY VARCHAR(80),
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	primary key (CLIENT_ID)
);
CREATE TABLE IF NOT EXISTS DEPARTMENTS_DETAIL (
	DEPT_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	DEPT_NAME VARCHAR(100) NOT NULL,
	BU_ID NUMBER(38,0),
	HEAD_USER_ID NUMBER(38,0),
	primary key (DEPT_ID)
);
CREATE TABLE IF NOT EXISTS EMPLOYEES (
	EMPLOYEE_ID NUMBER(38,0) NOT NULL,
	FIRST_NAME VARCHAR(80) NOT NULL,
	LAST_NAME VARCHAR(80) NOT NULL,
	EMAIL VARCHAR(150),
	DEPARTMENT VARCHAR(100),
	TITLE VARCHAR(150),
	LOCATION VARCHAR(100),
	STATUS VARCHAR(20),
	HIRE_DATE DATE,
	TERMINATION_DATE DATE,
	LAST_WORKING_DAY DATE,
	TERMINATION_REASON VARCHAR(200),
	TERMINATION_TYPE VARCHAR(50),
	MANAGER_ID NUMBER(38,0),
	BUSINESS_UNIT_ID NUMBER(38,0),
	SUB_DEPT_ID NUMBER(38,0),
	TEAM_ID NUMBER(38,0),
	LATTICE_ID VARCHAR(64),
	OMNI_EMPLOYEE_ID VARCHAR(64),  -- OmniHR (Omni API v1) employee lineage id; was FRESHTEAM_ID
	primary key (EMPLOYEE_ID)
);
CREATE TABLE IF NOT EXISTS EMPLOYEES_HISTORY (
	HISTORY_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	EMPLOYEE_ID NUMBER(38,0),
	CHANGE_TYPE VARCHAR(40),
	FROM_VALUE VARCHAR(200),
	TO_VALUE VARCHAR(200),
	EFFECTIVE_DATE DATE,
	REASON VARCHAR(300),
	primary key (HISTORY_ID)
);
CREATE TABLE IF NOT EXISTS EMPLOYEE_CERTIFICATIONS (
	CERT_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	EMPLOYEE_ID NUMBER(38,0),
	CERTIFICATION_NAME VARCHAR(150),
	ISSUING_BODY VARCHAR(120),
	ISSUE_DATE DATE,
	EXPIRY_DATE DATE,
	STATUS VARCHAR(20),
	SKILL_CATEGORY VARCHAR(80),
	primary key (CERT_ID)
);
CREATE TABLE IF NOT EXISTS EMPLOYEE_COMPENSATION_DETAILS (
	EMPLOYEE_ID NUMBER(38,0) NOT NULL,
	STOCK_OPTIONS NUMBER(38,0),
	SHARES_VESTED NUMBER(38,0),
	EQUITY_VALUE_ESTIMATE NUMBER(38,0),
	EMPLOYER_MATCH_PCT NUMBER(5,2),
	PAY_FREQUENCY VARCHAR(20),
	OVERTIME_ELIGIBLE BOOLEAN,
	SIGNING_BONUS NUMBER(38,0),
	TRAINING_BUDGET NUMBER(38,0),
	TRAINING_BUDGET_USED NUMBER(38,0),
	ANNUAL_LEAVE_BALANCE NUMBER(5,1),
	SICK_LEAVE_BALANCE NUMBER(5,1),
	PERSONAL_LEAVE_BALANCE NUMBER(5,1),
	LAST_PROMOTION_DATE DATE,
	LAST_PROMOTION_FROM VARCHAR(150),
	NEXT_REVIEW_DATE DATE,
	PIP_STATUS VARCHAR(40) DEFAULT 'None',
	PIP_START_DATE DATE,
	PIP_END_DATE DATE,
	primary key (EMPLOYEE_ID)
);
CREATE TABLE IF NOT EXISTS EMPLOYEE_FIELDS (
	EMPLOYEE_ID NUMBER(38,0) NOT NULL,
	EMPLOYMENT_TYPE VARCHAR(40),
	TEAM VARCHAR(100),
	PHONE VARCHAR(40),
	PERSONAL_EMAIL VARCHAR(150),
	NATIONALITY VARCHAR(80),
	GENDER VARCHAR(40),
	DATE_OF_BIRTH DATE,
	BLOOD_GROUP VARCHAR(10),
	EMERGENCY_CONTACT_NAME VARCHAR(120),
	EMERGENCY_CONTACT_PHONE VARCHAR(40),
	NOTICE_PERIOD_DAYS NUMBER(38,0),
	primary key (EMPLOYEE_ID)
);
CREATE TABLE IF NOT EXISTS EMPLOYEE_NOTES (
	NOTE_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	EMPLOYEE_ID NUMBER(38,0),
	NOTE_DATE DATE,
	NOTE_TYPE VARCHAR(50),
	CONTENT VARCHAR(2000),
	PRIORITY VARCHAR(20),
	IS_RESOLVED BOOLEAN DEFAULT FALSE,
	CREATED_BY NUMBER(38,0),
	TAGS VARCHAR(200),
	primary key (NOTE_ID)
);
CREATE TABLE IF NOT EXISTS EMPLOYEE_PII (
	EMPLOYEE_ID NUMBER(38,0) NOT NULL,
	SSN VARCHAR(20),
	PASSPORT_NUMBER VARCHAR(30),
	PASSPORT_EXPIRY DATE,
	MARITAL_STATUS VARCHAR(20),
	DEPENDENTS_COUNT NUMBER(38,0),
	PREFERRED_PRONOUNS VARCHAR(30),
	VISA_STATUS VARCHAR(50),
	VISA_EXPIRY DATE,
	DRIVERS_LICENSE VARCHAR(30),
	DRIVERS_LICENSE_STATE VARCHAR(10),
	DRIVERS_LICENSE_EXPIRY DATE,
	HOME_ADDRESS VARCHAR(200),
	CITY VARCHAR(80),
	STATE VARCHAR(40),
	ZIP_CODE VARCHAR(20),
	COUNTRY VARCHAR(80),
	LINKEDIN_URL VARCHAR(200),
	HEALTH_INSURANCE_PLAN VARCHAR(80),
	HEALTH_INSURANCE_ID VARCHAR(40),
	DENTAL_PLAN VARCHAR(80),
	VISION_PLAN VARCHAR(80),
	LIFE_INSURANCE_COVERAGE NUMBER(38,0),
	BANK_NAME VARCHAR(80),
	BANK_ACCOUNT_LAST4 VARCHAR(8),
	ETHNICITY VARCHAR(60),
	VETERAN_STATUS VARCHAR(40),
	DISABILITY_STATUS VARCHAR(40),
	T_SHIRT_SIZE VARCHAR(10),
	DIETARY_RESTRICTIONS VARCHAR(120),
	primary key (EMPLOYEE_ID)
);
CREATE TABLE IF NOT EXISTS ESTIMATES (
	ESTIMATE_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	CLIENT_ID NUMBER(38,0),
	AMOUNT NUMBER(12,2),
	ISSUE_DATE DATE,
	STATUS VARCHAR(20),
	primary key (ESTIMATE_ID)
);
CREATE TABLE IF NOT EXISTS EXPENSE_ENTRIES (
	EXPENSE_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	EMPLOYEE_ID NUMBER(38,0),
	PROJECT_ID NUMBER(38,0),
	EXPENSE_DATE DATE,
	CATEGORY VARCHAR(60),
	AMOUNT NUMBER(10,2),
	IS_BILLABLE BOOLEAN,
	NOTES VARCHAR(300),
	primary key (EXPENSE_ID)
);
CREATE TABLE IF NOT EXISTS HARVEST_USERS (
	USER_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	EMPLOYEE_ID NUMBER(38,0),
	FIRST_NAME VARCHAR(80),
	LAST_NAME VARCHAR(80),
	ROLES VARCHAR(200),
	DEFAULT_HOURLY_RATE NUMBER(8,2),
	COST_RATE NUMBER(8,2),
	WEEKLY_CAPACITY NUMBER(38,0),
	primary key (USER_ID)
);
CREATE TABLE IF NOT EXISTS HEADCOUNT_PLAN (
	PLAN_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	MONTH DATE,
	BUSINESS_UNIT_ID NUMBER(38,0),
	DEPARTMENT VARCHAR(100),
	PLANNED_FTE NUMBER(38,0) DEFAULT 0,
	PLANNED_CONTRACTORS NUMBER(38,0) DEFAULT 0,
	PLANNED_MANAGED NUMBER(38,0) DEFAULT 0,
	primary key (PLAN_ID)
);
CREATE TABLE IF NOT EXISTS INVOICES (
	INVOICE_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	CLIENT_ID NUMBER(38,0),
	AMOUNT NUMBER(12,2),
	ISSUE_DATE DATE,
	DUE_DATE DATE,
	STATUS VARCHAR(20),
	primary key (INVOICE_ID)
);
CREATE TABLE IF NOT EXISTS INVOICE_LINE_ITEMS (
	LINE_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	INVOICE_ID NUMBER(38,0),
	DESCRIPTION VARCHAR(200),
	QUANTITY NUMBER(8,2),
	UNIT_PRICE NUMBER(10,2),
	AMOUNT NUMBER(12,2),
	primary key (LINE_ID)
);
CREATE TABLE IF NOT EXISTS JOB_POSTINGS (
	JOB_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	TITLE VARCHAR(150),
	DEPARTMENT VARCHAR(100),
	JOB_TYPE VARCHAR(40),
	LOCATION VARCHAR(100),
	OPENINGS NUMBER(38,0) DEFAULT 1,
	APPLICANTS_COUNT NUMBER(38,0) DEFAULT 0,
	SALARY_MIN NUMBER(38,0),
	SALARY_MAX NUMBER(38,0),
	STATUS VARCHAR(20),
	CREATED_DATE DATE,
	primary key (JOB_ID)
);
CREATE TABLE IF NOT EXISTS LEAVE_REQUESTS (
	REQUEST_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	EMPLOYEE_ID NUMBER(38,0),
	LEAVE_TYPE VARCHAR(40),
	START_DATE DATE,
	END_DATE DATE,
	DAYS NUMBER(4,1),
	STATUS VARCHAR(20),
	REASON VARCHAR(300),
	primary key (REQUEST_ID)
);
CREATE TABLE IF NOT EXISTS ONBOARDING_TASKS (
	TASK_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	EMPLOYEE_ID NUMBER(38,0),
	TASK_NAME VARCHAR(150),
	DUE_DATE DATE,
	STATUS VARCHAR(20),
	ASSIGNED_TO NUMBER(38,0),
	primary key (TASK_ID)
);
CREATE TABLE IF NOT EXISTS PERFORMANCE_REVIEWS (
	REVIEW_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	EMPLOYEE_ID NUMBER(38,0),
	REVIEW_DATE DATE,
	REVIEW_PERIOD VARCHAR(40),
	RATING NUMBER(2,1),
	SENTIMENT VARCHAR(20),
	SENTIMENT_SCORE NUMBER(4,3),
	GOALS_MET NUMBER(38,0),
	GOALS_TOTAL NUMBER(38,0),
	MANAGER_COMMENTS VARCHAR(2000),
	primary key (REVIEW_ID)
);
CREATE TABLE IF NOT EXISTS PROJECTS (
	PROJECT_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	PROJECT_NAME VARCHAR(150),
	CLIENT VARCHAR(120),
	CLIENT_ID NUMBER(38,0),
	STATUS VARCHAR(20),
	START_DATE DATE,
	END_DATE DATE,
	BUDGET NUMBER(12,2),
	HOURLY_RATE NUMBER(8,2),
	FEES NUMBER(12,2),
	COST_BUDGET NUMBER(12,2),
	BUDGET_BY VARCHAR(20),
	IS_BILLABLE BOOLEAN DEFAULT TRUE,
	primary key (PROJECT_ID)
);
CREATE TABLE IF NOT EXISTS PROJECT_ASSIGNMENTS (
	ASSIGNMENT_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	EMPLOYEE_ID NUMBER(38,0),
	PROJECT_ID NUMBER(38,0),
	ROLE VARCHAR(80),
	ALLOCATION_PCT NUMBER(5,2),
	START_DATE DATE,
	END_DATE DATE,
	HOURLY_RATE NUMBER(8,2),
	BUDGET NUMBER(12,2),
	IS_PROJECT_MANAGER BOOLEAN DEFAULT FALSE,
	primary key (ASSIGNMENT_ID)
);
CREATE TABLE IF NOT EXISTS PROJECT_BUDGETS (
	BUDGET_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	PROJECT_ID NUMBER(38,0),
	BUDGET_AMOUNT NUMBER(12,2),
	AMOUNT_SPENT NUMBER(12,2),
	AMOUNT_REMAINING NUMBER(12,2),
	HOURS_SPENT NUMBER(8,2),
	HOURS_REMAINING NUMBER(8,2),
	primary key (BUDGET_ID)
);
CREATE TABLE IF NOT EXISTS PROJECT_TASKS (
	PT_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	PROJECT_ID NUMBER(38,0),
	TASK_ID NUMBER(38,0),
	HOURLY_RATE NUMBER(8,2),
	BUDGET NUMBER(12,2),
	primary key (PT_ID)
);
CREATE TABLE IF NOT EXISTS SALARY (
	SALARY_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	EMPLOYEE_ID NUMBER(38,0),
	EFFECTIVE_DATE DATE,
	BASE_SALARY NUMBER(38,0),
	BONUS NUMBER(38,0) DEFAULT 0,
	primary key (SALARY_ID)
);
CREATE TABLE IF NOT EXISTS SUB_DEPARTMENTS (
	SUB_DEPT_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	NAME VARCHAR(100) NOT NULL,
	DEPT_ID NUMBER(38,0),
	BU_ID NUMBER(38,0),
	primary key (SUB_DEPT_ID)
);
CREATE TABLE IF NOT EXISTS TASKS (
	TASK_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	TASK_NAME VARCHAR(80),
	IS_BILLABLE_DEFAULT BOOLEAN DEFAULT TRUE,
	primary key (TASK_ID)
);
CREATE TABLE IF NOT EXISTS TEAMS (
	TEAM_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	NAME VARCHAR(100) NOT NULL,
	SUB_DEPT_ID NUMBER(38,0),
	DEPT_ID NUMBER(38,0),
	BU_ID NUMBER(38,0),
	primary key (TEAM_ID)
);
CREATE TABLE IF NOT EXISTS TIME_ENTRIES (
	ENTRY_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	EMPLOYEE_ID NUMBER(38,0),
	PROJECT_ID NUMBER(38,0),
	TASK_ID NUMBER(38,0),
	SPENT_DATE DATE,
	HOURS NUMBER(5,2),
	IS_BILLABLE BOOLEAN,
	NOTES VARCHAR(500),
	primary key (ENTRY_ID)
);
CREATE TABLE IF NOT EXISTS USER_ASSIGNMENTS (
	UA_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	USER_ID NUMBER(38,0),
	PROJECT_ID NUMBER(38,0),
	IS_PROJECT_MANAGER BOOLEAN DEFAULT FALSE,
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	HOURLY_RATE NUMBER(8,2),
	BUDGET NUMBER(12,2),
	primary key (UA_ID)
);
CREATE TABLE IF NOT EXISTS UTILIZATION (
	UTIL_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	EMPLOYEE_ID NUMBER(38,0),
	MONTH DATE,
	UTILIZATION_RATE NUMBER(5,2),
	TARGET_RATE NUMBER(5,2) DEFAULT 80,
	primary key (UTIL_ID)
);

-- 5) RAG chat backend tables (5) ------------------------------------
--    CHAT_SESSIONS / CHAT_MESSAGES   : per-user chat persistence (app writes at runtime)
--    DOCUMENT_CHUNKS / DOC_INGEST_LOG: populated by 01_document_ingestion.sql
--    COMPANY_KNOWLEDGE_BASE          : the original curated KB (kept for lineage; the
--                                      live chat now indexes DOCUMENT_CHUNKS instead)
CREATE TABLE IF NOT EXISTS CHAT_MESSAGES (
	MESSAGE_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	SESSION_ID NUMBER(38,0),
	USERNAME VARCHAR(150),
	ROLE VARCHAR(20),
	CONTENT VARCHAR(16777216),
	SOURCES VARCHAR(16777216),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (MESSAGE_ID)
);
CREATE TABLE IF NOT EXISTS CHAT_SESSIONS (
	SESSION_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	USERNAME VARCHAR(150),
	SESSION_NAME VARCHAR(200),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	LAST_ACTIVE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (SESSION_ID)
);
CREATE TABLE IF NOT EXISTS COMPANY_KNOWLEDGE_BASE (
	KB_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	TITLE VARCHAR(200),
	CATEGORY VARCHAR(80),
	AUDIENCE VARCHAR(40),
	CONTENT VARCHAR(16777216),
	primary key (KB_ID)
);
CREATE TABLE IF NOT EXISTS DOCUMENT_CHUNKS (
	CHUNK_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	FILE_NAME VARCHAR(16777216),
	TITLE VARCHAR(16777216),
	CATEGORY VARCHAR(16777216),
	CHUNK_INDEX NUMBER(38,0),
	CONTENT VARCHAR(16777216),
	INGESTED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (CHUNK_ID)
);
CREATE TABLE IF NOT EXISTS DOC_INGEST_LOG (
	RUN_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	METADATA_ACTION VARCHAR(16777216),
	FILE_NAME VARCHAR(16777216)
);

-- 6) Data (structure-only setup) ------------------------------------
-- This script intentionally creates NO rows. The live account already holds
-- the synthetic demo data (~5,305 rows across 36 tables). To repopulate an
-- empty rebuild, PUT per-table CSVs to @DEMO_SEED_STAGE and:
--   COPY INTO <TABLE> FROM @DEMO_SEED_STAGE/<TABLE>.csv
--     FILE_FORMAT = (TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1 NULL_IF=('','NULL','null')) FORCE=TRUE;
-- (Or ask Cortex Code to dump the live data to INSERTs/CSVs.)

-- 7) Sanity check ----------------------------------------------------
SHOW TABLES IN SCHEMA DEMO_EMPLOYEE_APP.PUBLIC;
