-- =====================================================================
-- 03_silver.sql  --  SILVER layer: typed tables + Bronze->Silver flatten
--
-- The "Transform" of the medallion. Defines SILVER.* (typed/cleaned tables, DDL
-- mirrors the captured 00_setup.sql data tables) and flattens each BRONZE.* VARIANT
-- table into it. Driven by BRONZE.BRONZE_ENDPOINTS + SILVER.SILVER_FIELD_MAP (the
-- field-path map for the two NESTED endpoints; flat endpoints map automatically).
--
-- SAFE: SP_FLATTEN skips a table whose Bronze is empty, so a partial ingest never
-- wipes a Silver table. INSERT OVERWRITE makes Silver exactly reflect Bronze.
--
-- NOTE: SILVER.* mirrors the data-table DDL in 00_setup.sql — keep the two in sync.
-- Run as ACCOUNTADMIN.
-- =====================================================================
USE ROLE ACCOUNTADMIN;
USE DATABASE DEMO_EMPLOYEE_APP;
USE WAREHOUSE DEMO_WH;
CREATE SCHEMA IF NOT EXISTS SILVER;

-- 1) Typed SILVER tables (empty; filled by SP_BUILD_SILVER) -----------
CREATE TABLE IF NOT EXISTS SILVER.BUSINESS_UNITS (
	BU_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	NAME VARCHAR(100) NOT NULL,
	HEAD_USER_ID NUMBER(38,0),
	primary key (BU_ID)
);
CREATE TABLE IF NOT EXISTS SILVER.DEPARTMENTS_DETAIL (
	DEPT_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	DEPT_NAME VARCHAR(100) NOT NULL,
	BU_ID NUMBER(38,0),
	HEAD_USER_ID NUMBER(38,0),
	primary key (DEPT_ID)
);
CREATE TABLE IF NOT EXISTS SILVER.SUB_DEPARTMENTS (
	SUB_DEPT_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	NAME VARCHAR(100) NOT NULL,
	DEPT_ID NUMBER(38,0),
	BU_ID NUMBER(38,0),
	primary key (SUB_DEPT_ID)
);
CREATE TABLE IF NOT EXISTS SILVER.TEAMS (
	TEAM_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	NAME VARCHAR(100) NOT NULL,
	SUB_DEPT_ID NUMBER(38,0),
	DEPT_ID NUMBER(38,0),
	BU_ID NUMBER(38,0),
	primary key (TEAM_ID)
);
CREATE TABLE IF NOT EXISTS SILVER.EMPLOYEES (
	EMPLOYEE_ID NUMBER(38,0) NOT NULL,
	FIRST_NAME VARCHAR(80) NOT NULL,
	LAST_NAME VARCHAR(80) NOT NULL,
	EMAIL VARCHAR(150),
	DEPARTMENT VARCHAR(100),
	TITLE VARCHAR(150),
	LOCATION VARCHAR(100),
	STATUS VARCHAR(20),
	HIRE_DATE DATE,
	TERMINATION_DATE DATE,
	LAST_WORKING_DAY DATE,
	TERMINATION_REASON VARCHAR(200),
	TERMINATION_TYPE VARCHAR(50),
	MANAGER_ID NUMBER(38,0),
	BUSINESS_UNIT_ID NUMBER(38,0),
	SUB_DEPT_ID NUMBER(38,0),
	TEAM_ID NUMBER(38,0),
	LATTICE_ID VARCHAR(64),
	OMNI_EMPLOYEE_ID VARCHAR(64),  -- OmniHR (Omni API v1) employee lineage id; was FRESHTEAM_ID
	primary key (EMPLOYEE_ID)
);
CREATE TABLE IF NOT EXISTS SILVER.EMPLOYEE_FIELDS (
	EMPLOYEE_ID NUMBER(38,0) NOT NULL,
	EMPLOYMENT_TYPE VARCHAR(40),
	TEAM VARCHAR(100),
	PHONE VARCHAR(40),
	PERSONAL_EMAIL VARCHAR(150),
	NATIONALITY VARCHAR(80),
	GENDER VARCHAR(40),
	DATE_OF_BIRTH DATE,
	BLOOD_GROUP VARCHAR(10),
	EMERGENCY_CONTACT_NAME VARCHAR(120),
	EMERGENCY_CONTACT_PHONE VARCHAR(40),
	NOTICE_PERIOD_DAYS NUMBER(38,0),
	primary key (EMPLOYEE_ID)
);
CREATE TABLE IF NOT EXISTS SILVER.EMPLOYEE_PII (
	EMPLOYEE_ID NUMBER(38,0) NOT NULL,
	SSN VARCHAR(20),
	PASSPORT_NUMBER VARCHAR(30),
	PASSPORT_EXPIRY DATE,
	MARITAL_STATUS VARCHAR(20),
	DEPENDENTS_COUNT NUMBER(38,0),
	PREFERRED_PRONOUNS VARCHAR(30),
	VISA_STATUS VARCHAR(50),
	VISA_EXPIRY DATE,
	DRIVERS_LICENSE VARCHAR(30),
	DRIVERS_LICENSE_STATE VARCHAR(10),
	DRIVERS_LICENSE_EXPIRY DATE,
	HOME_ADDRESS VARCHAR(200),
	CITY VARCHAR(80),
	STATE VARCHAR(40),
	ZIP_CODE VARCHAR(20),
	COUNTRY VARCHAR(80),
	LINKEDIN_URL VARCHAR(200),
	HEALTH_INSURANCE_PLAN VARCHAR(80),
	HEALTH_INSURANCE_ID VARCHAR(40),
	DENTAL_PLAN VARCHAR(80),
	VISION_PLAN VARCHAR(80),
	LIFE_INSURANCE_COVERAGE NUMBER(38,0),
	BANK_NAME VARCHAR(80),
	BANK_ACCOUNT_LAST4 VARCHAR(8),
	ETHNICITY VARCHAR(60),
	VETERAN_STATUS VARCHAR(40),
	DISABILITY_STATUS VARCHAR(40),
	T_SHIRT_SIZE VARCHAR(10),
	DIETARY_RESTRICTIONS VARCHAR(120),
	primary key (EMPLOYEE_ID)
);
CREATE TABLE IF NOT EXISTS SILVER.EMPLOYEE_COMPENSATION_DETAILS (
	EMPLOYEE_ID NUMBER(38,0) NOT NULL,
	STOCK_OPTIONS NUMBER(38,0),
	SHARES_VESTED NUMBER(38,0),
	EQUITY_VALUE_ESTIMATE NUMBER(38,0),
	EMPLOYER_MATCH_PCT NUMBER(5,2),
	PAY_FREQUENCY VARCHAR(20),
	OVERTIME_ELIGIBLE BOOLEAN,
	SIGNING_BONUS NUMBER(38,0),
	TRAINING_BUDGET NUMBER(38,0),
	TRAINING_BUDGET_USED NUMBER(38,0),
	ANNUAL_LEAVE_BALANCE NUMBER(5,1),
	SICK_LEAVE_BALANCE NUMBER(5,1),
	PERSONAL_LEAVE_BALANCE NUMBER(5,1),
	LAST_PROMOTION_DATE DATE,
	LAST_PROMOTION_FROM VARCHAR(150),
	NEXT_REVIEW_DATE DATE,
	PIP_STATUS VARCHAR(40) DEFAULT 'None',
	PIP_START_DATE DATE,
	PIP_END_DATE DATE,
	primary key (EMPLOYEE_ID)
);
CREATE TABLE IF NOT EXISTS SILVER.EMPLOYEE_CERTIFICATIONS (
	CERT_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	EMPLOYEE_ID NUMBER(38,0),
	CERTIFICATION_NAME VARCHAR(150),
	ISSUING_BODY VARCHAR(120),
	ISSUE_DATE DATE,
	EXPIRY_DATE DATE,
	STATUS VARCHAR(20),
	SKILL_CATEGORY VARCHAR(80),
	primary key (CERT_ID)
);
CREATE TABLE IF NOT EXISTS SILVER.SALARY (
	SALARY_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	EMPLOYEE_ID NUMBER(38,0),
	EFFECTIVE_DATE DATE,
	BASE_SALARY NUMBER(38,0),
	BONUS NUMBER(38,0) DEFAULT 0,
	primary key (SALARY_ID)
);
CREATE TABLE IF NOT EXISTS SILVER.EMPLOYEES_HISTORY (
	HISTORY_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	EMPLOYEE_ID NUMBER(38,0),
	CHANGE_TYPE VARCHAR(40),
	FROM_VALUE VARCHAR(200),
	TO_VALUE VARCHAR(200),
	EFFECTIVE_DATE DATE,
	REASON VARCHAR(300),
	primary key (HISTORY_ID)
);
CREATE TABLE IF NOT EXISTS SILVER.HEADCOUNT_PLAN (
	PLAN_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	MONTH DATE,
	BUSINESS_UNIT_ID NUMBER(38,0),
	DEPARTMENT VARCHAR(100),
	PLANNED_FTE NUMBER(38,0) DEFAULT 0,
	PLANNED_CONTRACTORS NUMBER(38,0) DEFAULT 0,
	PLANNED_MANAGED NUMBER(38,0) DEFAULT 0,
	primary key (PLAN_ID)
);
CREATE TABLE IF NOT EXISTS SILVER.CANDIDATE_SOURCE_CATEGORIES (
	CATEGORY_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	NAME VARCHAR(40),
	primary key (CATEGORY_ID)
);
CREATE TABLE IF NOT EXISTS SILVER.CANDIDATE_SOURCES (
	SOURCE_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	NAME VARCHAR(60),
	CATEGORY VARCHAR(40),
	primary key (SOURCE_ID)
);
CREATE TABLE IF NOT EXISTS SILVER.JOB_POSTINGS (
	JOB_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	TITLE VARCHAR(150),
	DEPARTMENT VARCHAR(100),
	JOB_TYPE VARCHAR(40),
	LOCATION VARCHAR(100),
	OPENINGS NUMBER(38,0) DEFAULT 1,
	APPLICANTS_COUNT NUMBER(38,0) DEFAULT 0,
	SALARY_MIN NUMBER(38,0),
	SALARY_MAX NUMBER(38,0),
	STATUS VARCHAR(20),
	CREATED_DATE DATE,
	primary key (JOB_ID)
);
CREATE TABLE IF NOT EXISTS SILVER.CANDIDATES (
	CANDIDATE_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	JOB_ID NUMBER(38,0),
	FIRST_NAME VARCHAR(80),
	LAST_NAME VARCHAR(80),
	EMAIL VARCHAR(150),
	STAGE VARCHAR(40),
	STATUS VARCHAR(20),
	SOURCE VARCHAR(60),
	APPLIED_DATE DATE,
	RATING NUMBER(2,1),
	primary key (CANDIDATE_ID)
);
CREATE TABLE IF NOT EXISTS SILVER.ONBOARDING_TASKS (
	TASK_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	EMPLOYEE_ID NUMBER(38,0),
	TASK_NAME VARCHAR(150),
	DUE_DATE DATE,
	STATUS VARCHAR(20),
	ASSIGNED_TO NUMBER(38,0),
	primary key (TASK_ID)
);
CREATE TABLE IF NOT EXISTS SILVER.LEAVE_REQUESTS (
	REQUEST_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	EMPLOYEE_ID NUMBER(38,0),
	LEAVE_TYPE VARCHAR(40),
	START_DATE DATE,
	END_DATE DATE,
	DAYS NUMBER(4,1),
	STATUS VARCHAR(20),
	REASON VARCHAR(300),
	primary key (REQUEST_ID)
);
CREATE TABLE IF NOT EXISTS SILVER.CLIENTS (
	CLIENT_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	NAME VARCHAR(120),
	INDUSTRY VARCHAR(80),
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	primary key (CLIENT_ID)
);
CREATE TABLE IF NOT EXISTS SILVER.PROJECTS (
	PROJECT_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	PROJECT_NAME VARCHAR(150),
	CLIENT VARCHAR(120),
	CLIENT_ID NUMBER(38,0),
	STATUS VARCHAR(20),
	START_DATE DATE,
	END_DATE DATE,
	BUDGET NUMBER(12,2),
	HOURLY_RATE NUMBER(8,2),
	FEES NUMBER(12,2),
	COST_BUDGET NUMBER(12,2),
	BUDGET_BY VARCHAR(20),
	IS_BILLABLE BOOLEAN DEFAULT TRUE,
	primary key (PROJECT_ID)
);
CREATE TABLE IF NOT EXISTS SILVER.TASKS (
	TASK_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	TASK_NAME VARCHAR(80),
	IS_BILLABLE_DEFAULT BOOLEAN DEFAULT TRUE,
	primary key (TASK_ID)
);
CREATE TABLE IF NOT EXISTS SILVER.HARVEST_USERS (
	USER_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	EMPLOYEE_ID NUMBER(38,0),
	FIRST_NAME VARCHAR(80),
	LAST_NAME VARCHAR(80),
	ROLES VARCHAR(200),
	DEFAULT_HOURLY_RATE NUMBER(8,2),
	COST_RATE NUMBER(8,2),
	WEEKLY_CAPACITY NUMBER(38,0),
	primary key (USER_ID)
);
CREATE TABLE IF NOT EXISTS SILVER.PROJECT_ASSIGNMENTS (
	ASSIGNMENT_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	EMPLOYEE_ID NUMBER(38,0),
	PROJECT_ID NUMBER(38,0),
	ROLE VARCHAR(80),
	ALLOCATION_PCT NUMBER(5,2),
	START_DATE DATE,
	END_DATE DATE,
	HOURLY_RATE NUMBER(8,2),
	BUDGET NUMBER(12,2),
	IS_PROJECT_MANAGER BOOLEAN DEFAULT FALSE,
	primary key (ASSIGNMENT_ID)
);
CREATE TABLE IF NOT EXISTS SILVER.PROJECT_BUDGETS (
	BUDGET_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	PROJECT_ID NUMBER(38,0),
	BUDGET_AMOUNT NUMBER(12,2),
	AMOUNT_SPENT NUMBER(12,2),
	AMOUNT_REMAINING NUMBER(12,2),
	HOURS_SPENT NUMBER(8,2),
	HOURS_REMAINING NUMBER(8,2),
	primary key (BUDGET_ID)
);
CREATE TABLE IF NOT EXISTS SILVER.PROJECT_TASKS (
	PT_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	PROJECT_ID NUMBER(38,0),
	TASK_ID NUMBER(38,0),
	HOURLY_RATE NUMBER(8,2),
	BUDGET NUMBER(12,2),
	primary key (PT_ID)
);
CREATE TABLE IF NOT EXISTS SILVER.USER_ASSIGNMENTS (
	UA_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	USER_ID NUMBER(38,0),
	PROJECT_ID NUMBER(38,0),
	IS_PROJECT_MANAGER BOOLEAN DEFAULT FALSE,
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	HOURLY_RATE NUMBER(8,2),
	BUDGET NUMBER(12,2),
	primary key (UA_ID)
);
CREATE TABLE IF NOT EXISTS SILVER.TIME_ENTRIES (
	ENTRY_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	EMPLOYEE_ID NUMBER(38,0),
	PROJECT_ID NUMBER(38,0),
	TASK_ID NUMBER(38,0),
	SPENT_DATE DATE,
	HOURS NUMBER(5,2),
	IS_BILLABLE BOOLEAN,
	NOTES VARCHAR(500),
	primary key (ENTRY_ID)
);
CREATE TABLE IF NOT EXISTS SILVER.EXPENSE_ENTRIES (
	EXPENSE_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	EMPLOYEE_ID NUMBER(38,0),
	PROJECT_ID NUMBER(38,0),
	EXPENSE_DATE DATE,
	CATEGORY VARCHAR(60),
	AMOUNT NUMBER(10,2),
	IS_BILLABLE BOOLEAN,
	NOTES VARCHAR(300),
	primary key (EXPENSE_ID)
);
CREATE TABLE IF NOT EXISTS SILVER.AVAILABILITY (
	AVAIL_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	EMPLOYEE_ID NUMBER(38,0),
	AVAIL_DATE DATE,
	STATUS VARCHAR(20),
	primary key (AVAIL_ID)
);
CREATE TABLE IF NOT EXISTS SILVER.UTILIZATION (
	UTIL_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	EMPLOYEE_ID NUMBER(38,0),
	MONTH DATE,
	UTILIZATION_RATE NUMBER(5,2),
	TARGET_RATE NUMBER(5,2) DEFAULT 80,
	primary key (UTIL_ID)
);
CREATE TABLE IF NOT EXISTS SILVER.INVOICES (
	INVOICE_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	CLIENT_ID NUMBER(38,0),
	AMOUNT NUMBER(12,2),
	ISSUE_DATE DATE,
	DUE_DATE DATE,
	STATUS VARCHAR(20),
	primary key (INVOICE_ID)
);
CREATE TABLE IF NOT EXISTS SILVER.INVOICE_LINE_ITEMS (
	LINE_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	INVOICE_ID NUMBER(38,0),
	DESCRIPTION VARCHAR(200),
	QUANTITY NUMBER(8,2),
	UNIT_PRICE NUMBER(10,2),
	AMOUNT NUMBER(12,2),
	primary key (LINE_ID)
);
CREATE TABLE IF NOT EXISTS SILVER.ESTIMATES (
	ESTIMATE_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	CLIENT_ID NUMBER(38,0),
	AMOUNT NUMBER(12,2),
	ISSUE_DATE DATE,
	STATUS VARCHAR(20),
	primary key (ESTIMATE_ID)
);

-- 2) Field-path overrides for the NESTED endpoints --------------------
--    SILVER column -> JSON path inside PAYLOAD. Everything not listed uses
--    lower(column) (true for all flat endpoints). This IS the OmniHR/Harvest ->
--    warehouse lineage map (e.g. work_email -> EMAIL).
CREATE OR REPLACE TABLE SILVER.SILVER_FIELD_MAP (SILVER_TABLE STRING, COLUMN_NAME STRING, JSON_PATH STRING);
INSERT INTO SILVER.SILVER_FIELD_MAP (SILVER_TABLE, COLUMN_NAME, JSON_PATH) VALUES
  ('EMPLOYEES','EMPLOYEE_ID','id'),
  ('EMPLOYEES','EMAIL','work_email'),
  ('EMPLOYEES','STATUS','employment_status'),
  ('EMPLOYEES','HIRE_DATE','hired_date'),
  ('EMPLOYEES','TITLE','position.name'),
  ('EMPLOYEES','DEPARTMENT','department.name'),
  ('EMPLOYEES','LOCATION','work_location.name'),
  ('EMPLOYEES','MANAGER_ID','reporting_manager.id'),
  ('EMPLOYEES','SUB_DEPT_ID','sub_department_id'),
  ('EMPLOYEES','OMNI_EMPLOYEE_ID','system_id'),
  ('TIME_ENTRIES','ENTRY_ID','id'),
  ('TIME_ENTRIES','EMPLOYEE_ID','user.id'),
  ('TIME_ENTRIES','PROJECT_ID','project.id'),
  ('TIME_ENTRIES','TASK_ID','task.id'),
  ('TIME_ENTRIES','IS_BILLABLE','billable');

-- 3) Flatten ONE Bronze table into its Silver table --------------------
CREATE OR REPLACE PROCEDURE SILVER.SP_FLATTEN(TABLE_NAME STRING)
  RETURNS STRING LANGUAGE SQL
AS
$$
DECLARE
  cnt INT DEFAULT 0;
  collist STRING;
  sel STRING;
  bronze_fqn STRING;
BEGIN
  bronze_fqn := 'DEMO_EMPLOYEE_APP.BRONZE.' || :TABLE_NAME;
  SELECT COUNT(*) INTO :cnt FROM IDENTIFIER(:bronze_fqn);
  IF (cnt = 0) THEN
    RETURN :TABLE_NAME || ': skipped (bronze empty)';
  END IF;
  SELECT
      LISTAGG(c.COLUMN_NAME, ', ') WITHIN GROUP (ORDER BY c.ORDINAL_POSITION),
      LISTAGG('PAYLOAD:' || COALESCE(m.JSON_PATH, LOWER(c.COLUMN_NAME))
              || '::string AS ' || c.COLUMN_NAME, ', ')
        WITHIN GROUP (ORDER BY c.ORDINAL_POSITION)
    INTO :collist, :sel
  FROM DEMO_EMPLOYEE_APP.INFORMATION_SCHEMA.COLUMNS c
  LEFT JOIN DEMO_EMPLOYEE_APP.SILVER.SILVER_FIELD_MAP m
    ON m.SILVER_TABLE = c.TABLE_NAME AND m.COLUMN_NAME = c.COLUMN_NAME
  WHERE c.TABLE_SCHEMA = 'SILVER' AND c.TABLE_NAME = :TABLE_NAME;

  EXECUTE IMMEDIATE
    'INSERT OVERWRITE INTO DEMO_EMPLOYEE_APP.SILVER.' || :TABLE_NAME || ' (' || :collist || ') ' ||
    'SELECT ' || :sel || ' FROM DEMO_EMPLOYEE_APP.BRONZE.' || :TABLE_NAME;
  RETURN :TABLE_NAME || ': ' || cnt || ' rows';
END;
$$;

-- 4) Driver: flatten every endpoint that has Bronze data ---------------
CREATE OR REPLACE PROCEDURE SILVER.SP_BUILD_SILVER()
  RETURNS STRING LANGUAGE SQL
AS
$$
DECLARE
  n INT DEFAULT 0;
  c CURSOR FOR SELECT TABLE_NAME FROM DEMO_EMPLOYEE_APP.BRONZE.BRONZE_ENDPOINTS;
BEGIN
  FOR r IN c DO
    LET tn STRING := r.TABLE_NAME;
    CALL DEMO_EMPLOYEE_APP.SILVER.SP_FLATTEN(:tn);
    n := n + 1;
  END FOR;
  RETURN 'flattened ' || n || ' tables (empty bronze skipped)';
END;
$$;

-- =====================================================================
-- RUN (after Bronze is loaded by 02_bronze.sql):
--   CALL SILVER.SP_BUILD_SILVER();
-- VERIFY:
--   SELECT EMPLOYEE_ID, FIRST_NAME, EMAIL, TITLE, DEPARTMENT, OMNI_EMPLOYEE_ID
--     FROM SILVER.EMPLOYEES ORDER BY EMPLOYEE_ID LIMIT 5;
-- =====================================================================
