"""App bootstrap: page config, Snowpark session, and a cached read helper.

All identity (database, schema, model, company name, …) comes from app_config.py,
which is generated by render.py from the schema_spec. Nothing is hardcoded here.
"""
import streamlit as st
from snowflake.snowpark.context import get_active_session

import app_config as cfg

st.set_page_config(page_title=cfg.APP_TITLE, page_icon=cfg.APP_ICON, layout="wide")
session = get_active_session()


@st.cache_data(ttl=300)
def q(sql: str):
    """Cached read query → pandas DataFrame. Use only for read-only SELECTs with
    no user-supplied values (writes/parameterized queries go direct in rag_chat)."""
    return session.sql(sql).to_pandas()
