"""Generated by render.py — the ONLY place app identity lives. Do not hardcode elsewhere."""
DATABASE          = "DEMO_EMPLOYEE_APP"
SCHEMA            = "PUBLIC"
SERVICE_FQN       = "DEMO_EMPLOYEE_APP.PUBLIC.COMPANY_KB_SEARCH"
KB_TABLE          = "COMPANY_KNOWLEDGE_BASE"
KB_CONTENT_COL    = "CONTENT"
LLM_MODEL         = "mistral-large2"
COMPANY_NAME      = "Acme Solutions Inc"
APP_TITLE         = "Employee 360"
APP_ICON          = "👥"
ASSISTANT_INTRO   = "Ask me about company info, benefits, and events."
CHAT_PLACEHOLDER  = "Ask about company info, benefits, events..."
SUGGESTED_PROMPTS = ["What health plans do we offer?", "What is the PTO policy?", "When is the next all-hands?"]
SEARCH_COLUMNS    = ["CONTENT", "TITLE", "CATEGORY"]
SEARCH_LIMIT      = 3
