#!/usr/bin/env bash
# Generated by render.py — one-shot deploy. Pass your snow connection name:
#   ./run.sh <connection_name>
set -euo pipefail
CONN="${1:?usage: ./run.sh <snow_connection_name>}"
HERE="$(cd "$(dirname "$0")" && pwd)"
DB="DEMO_DYNAMICS_APP"; SCH="PUBLIC"; STAGE="DEMO_SEED_STAGE"

echo "1/6 bootstrap";    snow sql -c "$CONN" -f "$HERE/00_bootstrap.sql"
echo "2/6 ddl";          snow sql -c "$CONN" -f "$HERE/01_ddl.sql"
echo "3/6 upload CSVs";  for csv in "$HERE/../seed/"*.csv; do
  snow sql -c "$CONN" -q "PUT 'file://$csv' @$DB.$SCH.$STAGE/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;" >/dev/null
done
echo "4/6 load";         snow sql -c "$CONN" -f "$HERE/05_load_seed.sql"
echo "5/6 cortex search"; snow sql -c "$CONN" -f "$HERE/04_cortex_search.sql"
echo "6/6 verify row counts"
for t in CUSTOMERS PRODUCTS VENDORS SALES_ORDERS SALES_ORDER_LINES INVOICES GL_ENTRIES COMPANY_KNOWLEDGE_BASE; do
  n=$(snow sql -c "$CONN" --format json -q "SELECT COUNT(*) N FROM $DB.$SCH.$t;" | python3 -c "import sys,json;print(json.load(sys.stdin)[0]['N'])")
  if [ "$n" -eq 0 ]; then echo "  ✗ $t is EMPTY"; exit 1; else echo "  ✓ $t = $n"; fi
done
echo "Deploy the Streamlit app from ../app with:  snow streamlit deploy -c $CONN  (run inside ../app)"
