#!/usr/bin/env python3
"""Render a deployable bundle from a schema_spec.json.

Produces, under <out>/:
    deploy/00_bootstrap.sql      warehouse + database + schema + stages
    deploy/01_ddl.sql            CREATE TABLE for every table (incl. chat tables)
    deploy/04_cortex_search.sql  the Cortex Search service for the RAG knowledge base
    deploy/05_load_seed.sql      COPY INTO for every data table + row-count check
    deploy/run.sh                one-shot orchestrator (snow CLI)
    app/app_config.py            constants the Streamlit app reads (no hardcoding elsewhere)
    app/snowflake.yml            Streamlit deployment definition
    app/{_core,rag_chat,streamlit_app}.py, app/environment.yml   (copied from templates/app/)

Everything keys off the spec's `app` block, so object names never drift.

Usage:
    python render.py --spec path/to/schema_spec.json --out path/to/bundle/
"""
from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

TEMPLATES_DIR = Path(__file__).resolve().parent
APP_SRC = TEMPLATES_DIR / "app"

FILE_FORMAT = ("FILE_FORMAT=(TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='\"' "
               "SKIP_HEADER=1 NULL_IF=('','NULL','null'))")


def apply_defaults(spec: dict) -> dict:
    """Fill optional fields with their contract defaults (JSON Schema defaults are
    not auto-applied to data, so do it here before rendering)."""
    app = spec["app"]
    app.setdefault("schema", "PUBLIC")
    app.setdefault("role", "SYSADMIN")
    app.setdefault("stage", "DEMO_SEED_STAGE")
    kb = spec["knowledge_base"]
    kb.setdefault("service_name", "COMPANY_KB_SEARCH")
    kb.setdefault("target_lag", "1 hour")
    kb.setdefault("attributes", [])
    return spec


def ddl_column(c: dict) -> str:
    line = f"    {c['name']} {c['type']}"
    if c.get("autoincrement"):
        line += " AUTOINCREMENT"
    if c.get("pk"):
        line += " PRIMARY KEY"
    if not c.get("nullable", True) and not c.get("pk"):
        line += " NOT NULL"
    if "default" in c:
        line += f" DEFAULT {c['default']}"
    return line


def render_bootstrap(app: dict) -> str:
    return f"""-- Generated by render.py — bootstrap for {app['database']}
USE ROLE {app.get('role', 'SYSADMIN')};

CREATE WAREHOUSE IF NOT EXISTS {app['warehouse']}
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for {app['database']} demo + Streamlit';

CREATE DATABASE IF NOT EXISTS {app['database']} COMMENT = 'Cortex Dashboard Kit demo — synthetic data';
USE DATABASE {app['database']};
CREATE SCHEMA IF NOT EXISTS {app['schema']};
USE SCHEMA {app['database']}.{app['schema']};
USE WAREHOUSE {app['warehouse']};

CREATE STAGE IF NOT EXISTS {app['stage']}
    FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1 NULL_IF = ('', 'NULL', 'null'))
    COMMENT = 'Seed CSV landing zone';
CREATE STAGE IF NOT EXISTS STREAMLIT_STAGE COMMENT = 'Streamlit app artifacts';

SELECT CURRENT_ROLE() AS role, CURRENT_DATABASE() AS db, CURRENT_WAREHOUSE() AS wh;
"""


def render_ddl(spec: dict) -> str:
    app = spec["app"]
    out = [f"-- Generated by render.py — DDL for {app['database']}.{app['schema']}",
           f"USE ROLE {app.get('role', 'SYSADMIN')};",
           f"USE SCHEMA {app['database']}.{app['schema']};",
           f"USE WAREHOUSE {app['warehouse']};", ""]
    for t in spec["tables"]:
        cols = ",\n".join(ddl_column(c) for c in t["columns"])
        comment = f"  -- {t['grain']}" if t.get("grain") else ""
        out.append(f"CREATE OR REPLACE TABLE {t['name']} ({comment}\n{cols}\n);")
    out.append("")
    return "\n".join(out)


def render_cortex(spec: dict) -> str:
    app, kb = spec["app"], spec["knowledge_base"]
    attrs = ", ".join(kb.get("attributes", []))
    select_cols = ", ".join([kb["content_col"]] + kb.get("attributes", []))
    return f"""-- Generated by render.py — Cortex Search service for the RAG knowledge base.
-- Requires SNOWFLAKE.CORTEX_USER on the role.
USE ROLE {app.get('role', 'SYSADMIN')};
USE SCHEMA {app['database']}.{app['schema']};
USE WAREHOUSE {app['warehouse']};

CREATE OR REPLACE CORTEX SEARCH SERVICE {kb.get('service_name', 'COMPANY_KB_SEARCH')}
    ON {kb['content_col']}
    ATTRIBUTES {attrs}
    WAREHOUSE = {app['warehouse']}
    TARGET_LAG = '{kb.get('target_lag', '1 hour')}'
    EMBEDDING_MODEL = '{app['embed_model']}'
    AS SELECT {select_cols} FROM {app['database']}.{app['schema']}.{kb['table']};
"""


def render_load(spec: dict) -> str:
    app = spec["app"]
    out = [f"-- Generated by render.py — load seed CSVs into {app['database']}.{app['schema']}",
           f"USE ROLE {app.get('role', 'SYSADMIN')};",
           f"USE SCHEMA {app['database']}.{app['schema']};",
           f"USE WAREHOUSE {app['warehouse']};", ""]
    for t in spec["tables"]:
        if t.get("is_chat_table"):
            continue
        col_list = ",".join(c["name"] for c in t["columns"])
        out.append(f"COPY INTO {t['name']} ({col_list}) "
                   f"FROM @{app['stage']}/{t['name']}.csv {FILE_FORMAT} FORCE=TRUE;")
    out.append("")
    out.append("-- Post-load verification: every data table should be non-empty.")
    checks = "\n    UNION ALL ".join(
        f"SELECT '{t['name']}' AS TBL, COUNT(*) AS N FROM {t['name']}"
        for t in spec["tables"] if not t.get("is_chat_table"))
    out.append(f"SELECT * FROM (\n    {checks}\n) ORDER BY N ASC, TBL;")
    out.append("")
    return "\n".join(out)


def render_run_sh(spec: dict) -> str:
    app = spec["app"]
    data_tables = [t["name"] for t in spec["tables"] if not t.get("is_chat_table")]
    checks = " ".join(data_tables)
    return f"""#!/usr/bin/env bash
# Generated by render.py — one-shot deploy. Pass your snow connection name:
#   ./run.sh <connection_name>
set -euo pipefail
CONN="${{1:?usage: ./run.sh <snow_connection_name>}}"
HERE="$(cd "$(dirname "$0")" && pwd)"
DB="{app['database']}"; SCH="{app['schema']}"; STAGE="{app['stage']}"

echo "1/6 bootstrap";    snow sql -c "$CONN" -f "$HERE/00_bootstrap.sql"
echo "2/6 ddl";          snow sql -c "$CONN" -f "$HERE/01_ddl.sql"
echo "3/6 upload CSVs";  for csv in "$HERE/../seed/"*.csv; do
  snow sql -c "$CONN" -q "PUT 'file://$csv' @$DB.$SCH.$STAGE/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;" >/dev/null
done
echo "4/6 load";         snow sql -c "$CONN" -f "$HERE/05_load_seed.sql"
echo "5/6 cortex search"; snow sql -c "$CONN" -f "$HERE/04_cortex_search.sql"
echo "6/6 verify row counts"
for t in {checks}; do
  n=$(snow sql -c "$CONN" --format json -q "SELECT COUNT(*) N FROM $DB.$SCH.$t;" | python3 -c "import sys,json;print(json.load(sys.stdin)[0]['N'])")
  if [ "$n" -eq 0 ]; then echo "  ✗ $t is EMPTY"; exit 1; else echo "  ✓ $t = $n"; fi
done
echo "Deploy the Streamlit app from ../app with:  snow streamlit deploy -c $CONN  (run inside ../app)"
"""


def render_app_config(spec: dict) -> str:
    app, kb, dash = spec["app"], spec["knowledge_base"], spec["dashboard"]
    fqn = f"{app['database']}.{app['schema']}.{kb.get('service_name', 'COMPANY_KB_SEARCH')}"
    j = lambda v: json.dumps(v, ensure_ascii=False)
    return f'''"""Generated by render.py — the ONLY place app identity lives. Do not hardcode elsewhere."""
DATABASE          = {j(app['database'])}
SCHEMA            = {j(app['schema'])}
SERVICE_FQN       = {j(fqn)}
KB_TABLE          = {j(kb['table'])}
KB_CONTENT_COL    = {j(kb['content_col'])}
LLM_MODEL         = {j(app['llm_model'])}
COMPANY_NAME      = {j(app['company_name'])}
APP_TITLE         = {j(dash['title'])}
APP_ICON          = {j(dash.get('icon', '📊'))}
ASSISTANT_INTRO   = {j(dash.get('assistant_intro', 'Ask me a question.'))}
CHAT_PLACEHOLDER  = {j(dash.get('chat_placeholder', 'Ask a question...'))}
SUGGESTED_PROMPTS = {j(dash['suggested_prompts'])}
SEARCH_COLUMNS    = {j(dash.get('search_columns', ['CONTENT', 'TITLE', 'CATEGORY']))}
SEARCH_LIMIT      = {dash.get('search_limit', 3)}
'''


def render_snowflake_yml(spec: dict) -> str:
    app, dash = spec["app"], spec["dashboard"]
    name = "".join(ch if ch.isalnum() else "_" for ch in dash["title"]).upper() or "DASHBOARD_APP"
    return f"""definition_version: "2"
entities:
  dashboard_app:
    type: streamlit
    identifier:
      name: {name}
      schema: {app['schema']}
      database: {app['database']}
    title: "{dash['title']}"
    query_warehouse: {app['warehouse']}
    main_file: streamlit_app.py
    artifacts:
      - streamlit_app.py
      - _core.py
      - rag_chat.py
      - app_config.py
      - environment.yml
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--spec", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    spec = apply_defaults(json.loads(Path(args.spec).read_text()))
    out = Path(args.out)
    (out / "deploy").mkdir(parents=True, exist_ok=True)
    (out / "app").mkdir(parents=True, exist_ok=True)

    (out / "deploy" / "00_bootstrap.sql").write_text(render_bootstrap(spec["app"]))
    (out / "deploy" / "01_ddl.sql").write_text(render_ddl(spec))
    (out / "deploy" / "04_cortex_search.sql").write_text(render_cortex(spec))
    (out / "deploy" / "05_load_seed.sql").write_text(render_load(spec))
    run = out / "deploy" / "run.sh"
    run.write_text(render_run_sh(spec))
    run.chmod(0o755)

    (out / "app" / "app_config.py").write_text(render_app_config(spec), encoding="utf-8")
    (out / "app" / "snowflake.yml").write_text(render_snowflake_yml(spec), encoding="utf-8")
    for fname in ("_core.py", "rag_chat.py", "streamlit_app.py", "environment.yml"):
        shutil.copy(APP_SRC / fname, out / "app" / fname)

    print(f"✓ rendered bundle into {out}  (deploy/ + app/)")


if __name__ == "__main__":
    main()
